[workspace]
resolver = "2"

members = [
    "examples/anchor/ix_blank/*",
    "examples/anchor/ix_no_accounts/*",
    "examples/anchor/ix_no_accounts_pubkey_arg/*",
    "examples/anchor/ix_no_args/*",
    "examples/anchor/ix_no_privilege/*",
    "examples/anchor/drift/*",
    "examples/anchor/marinade/*",
    "examples/anchor/unstake_it/*",
    "solores",
    "test_utils"
]

[workspace.dependencies]
borsh = "^1.5"
bs58 = ">=0.5"
bytemuck = "^1.16"
clap = "4.5.14"
env_logger = "0.11.5"
heck = "0.5.0"
itertools = "^0.13"
lazy_static = "^1.5"
log = "0.4.22"
log-panics = "^2.1"
num-derive = "0.4.2"
num-traits = "^0.2"
prettyplease = "0.2.20"
proc-macro2 = "^1.0"
quote = "^1.0"
rand = "^0.8"
serde = "^1"
serde_json = "^1"
sha2 = "^0.10"
solana-cli-config = "^2.1"
solana-client = "^2.1"
solana-program = "^2.1"
solana-sdk = "^2.1"
syn = "^2.0"
thiserror = "^1.0"
tokio = "^1"
toml = "0.8.19"
void = "^1.0"

# workspace members
drift_interface = { path = "./examples/anchor/drift/drift_interface" }
marinade_finance_interface = { path = "./examples/anchor/marinade/marinade_finance_interface" }
test_utils = { path = "./test_utils" }
unstake_interface = { path = "./examples/anchor/unstake_it/unstake_interface" }
